# Generated by Django 3.0.2 on 2020-01-23 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='deletetoreport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default='')),
                ('body', models.TextField(default='')),
                ('writer', models.TextField(default='')),
                ('deletepk', models.TextField(default='')),
            ],
        ),
    ]
