# Generated by Django 3.0.2 on 2020-01-23 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200123_2214'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deletetoreport',
            old_name='title',
            new_name='writer',
        ),
    ]
