# Generated by Django 3.0.2 on 2020-01-23 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200123_2214'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='first',
            field=models.TextField(default='0'),
        ),
    ]
