# Generated by Django 3.0.2 on 2020-02-06 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_post_first'),
    ]

    operations = [
        migrations.CreateModel(
            name='commentreport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report', models.TextField(default='')),
                ('content', models.TextField(default='')),
                ('writer', models.TextField(default='')),
                ('deletepk', models.TextField(default='')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='first',
            field=models.TextField(default='0'),
        ),
        migrations.AddField(
            model_name='comment',
            name='report',
            field=models.TextField(default='0'),
        ),
    ]
